### PR TITLE
Add build target for .NET 6.0

### PR DESCRIPTION
**Pull request by yang-er**
Checklists for Pull requests
----------------------------

About pull request itself:
- [X] I am submitting a pull request :)
- [ ] I have already created an issue and referred to it in the commit message.
- [ ] My submission does one logical thing only (one bugfix, one new feature). 
      If want to supply multiple logical changes, I will submit multiple pull requests.
- [ ] I have read and understood CONTRIBUTING guide

Commits:
- [ ] My commits are logical, easily readable, with concise comments.

Licensing:
- [X] I am the author of submission or have been authorized by submission copyright holder to issue this pull request.

Branching:
- [X] My submission is based on master branch.
- [X] My submission is compatible with latest master branch updates (no conflicts, I did a rebase if it was necessary).
- [ ] The name of the branch I want to merge upstream is not 'master' (except for only the most trivial fixes, like typos and such).
- [ ] My branch name is *feature/my-new-not-for-productionfeature* (for new features).
- [ ] My branch name is *bugfix/i-fixed-your-crap-code* (for bugfixes).

Pull request description
------------------------
- Add build target for .NET 5.0 and 6.0
- Enable nullability checks

### CODE REVIEW

**Comment by blowdart** [comment]
This did give me a suitable kick to fix up the build pipeline and add a new target, but your PR adds nullable support, which breaks everything before it. It'd no longer compile for netstandard2, or 3.1 which makes this a big break.

While it's possible to manage this through manually adding attribute definitions what do you think adding nullable support adds to the package?

**Comment by yang-er** [comment]
Not sure why adding nullable check would break compilation. Maybe add `<LangVersion>8.0</LangVersion>` could resolve this.

Actually nullable check is not a must for this nuget package, but I just wanted to align with what ASP.NET Core 5.0 did. :D

**Comment by blowdart** [comment]
Ah fair enough. I've gotten a fixed build pipeline done over the weekend (along with code signing which has bugged me forever). That also added a 6.0 target, so it'll fulfil that requirement for you, I just need to get code coverage back and working again now coverlet supports deterministic builds and I'll release a new version. Probably later today or tomorrow.

**Comment by yang-er** [comment]
Yeah, take your time.

BTW, seems the netcoreapp3.1 version worked well on net6.0 (and I have kept the situation for about 3 months), but I am not sure if there was some hidden bug so I just wanted a target framework upgrade :D

**Comment by blowdart** [comment]
OK 2.2.3 is up with .NET 6 support, it's up to you if you want the rebase fun and games and consider nullable support worth adding :)

**Pull request closed without merging**
