### PR TITLE
Fix Synchronous operations are disallowed. Call WriteAsync or set All…

### PR DESCRIPTION
**Pull request by JeremyFerreira**
Checklists for Pull requests
----------------------------

About pull request itself:
- [X] I am submitting a pull request :)
- [ ] I have already created an issue and referred to it in the commit message.
- [X] My submission does one logical thing only (one bugfix, one new feature). 
      If want to supply multiple logical changes, I will submit multiple pull requests.
- [X] I have read and understood CONTRIBUTING guide

Commits:
- [X] My commits are logical, easily readable, with concise comments.

Licensing:
- [X] I am the author of submission or have been authorized by submission copyright holder to issue this pull request.

Branching:
- [X] My submission is based on master branch.
- [X] My submission is compatible with latest master branch updates (no conflicts, I did a rebase if it was necessary).
- [ ] The name of the branch I want to merge upstream is not 'master' (except for only the most trivial fixes, like typos and such).
- [ ] My branch name is *feature/my-new-not-for-productionfeature* (for new features).
- [X] My branch name is *bugfix/i-fixed-your-crap-code* (for bugfixes).

Pull request description
------------------------

I had an exception "`Synchronous operations are disallowed`". I think it should be async all the way instead of returning `Task.CompletedTask`.

Some tests are not passing, but does not concern my modification (As it was like this when forked from master).

### CODE REVIEW

**Comment by blowdart** [comment]
How long ago did you fork? All the tests are working here. Is it the cert tests that fail for you?

**Comment by blowdart** [comment]
@tratcher thoughts? JWT takes this approach, certs does not.

**Comment by Tratcher** [comment]
Yes, working with the request and response body should always be async.

That said, Challenge shouldn't write to the response body. It should throw or log and no-op.

**Comment by blowdart** [comment]
Ah in this case it's a "You're silly" message, so yea, in principle, in practice people don't check logs.

**Comment by Tratcher** [comment]
Then throw InvalidOperationException.

**Comment by blowdart** [comment]
That works, @JeremyFerreira what do you think?

**Comment by JeremyFerreira** [comment]
@blowdart I forked immediatly after seeing the "bug".

To me `InvalidOperationException` will not tell us what's the exact error.
Maybe I should create an exception especially for this error and come back with a new pull request ?

**Comment by Tratcher** [comment]
That's what the message is for?

**Comment by blowdart** [comment]
Plus the logs would have details. Relying on exception type to debug a configuration error feels a bit wrong.

**Comment by blowdart** [comment]
Oh there's a status code for this too, 421;

// 421 Misdirected Request
// The request was directed at a server that is not able to produce a response.
// This can be sent by a server that is not configured to produce responses for the combination of scheme and authority that are included in the request URI.
Response.StatusCode = 421;

So rather than throw, set the status code and log

**Pull request closed without merging**
